version: "3"

services:
  database:
    container_name: world-db
    image: mariadb:jammy
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=world-db
      - MYSQL_USER=sergio
      - MYSQL_PASSWORD=root
    volumes:
      - world-db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - database
    container_name: phpmyadmin-container
    image: phpmyadmin:5.2.1-apache
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=root

volumes:
  world-db:
  phpmyadmin:
